default: &default
  adapter: mysql2
  reconnect: false
  username: <%= ENV["MYSQL5_7_UESRNAME"] || 'root' %>
  password: <%= ENV["MYSQL5_7_ROOT_PASSWORD"] || 'pass' %>
  host: <%= ENV["MYSQL5_7_HOST"] || 'mysql' %>
  port: <%= ENV["MYSQL5_7_PORT"] || '3306' %>

development:
  <<: *default
  database: :stat_development

test:
  <<: *default
  database: :stat_test

production:
  <<: *default
  database: :stat_production
